# Sales Export 2019-2020 Data Analysis

## Objective
Analsing dataset for machine learning

## Import Libraries

In [2]:
import numpy as np
import pandas as pd

## Load dataset

In [3]:
df = pd.read_csv("Sales-Export_2019-2020.csv")

## Dataset's information

In [4]:
df.columns

Index(['country', ' order_value_EUR ', ' cost ', 'date', 'category',
       'customer_name', 'sales_manager', 'sales_rep', 'device_type',
       'order_id'],
      dtype='object')

In [5]:
df.head()

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
0,Sweden,"17,524.02",14122.61,2/12/2020,Books,Goldner-Dibbert,Maxie Marrow,Madelon Bront,Mobile,70-0511466
1,Finland,"116,563.40",92807.78,9/26/2019,Games,Hilll-Vandervort,Hube Corey,Wat Bowkley,Mobile,28-6585323
2,Portugal,"296,465.56",257480.34,7/11/2019,Clothing,Larkin-Collier,Celine Tumasian,Smitty Culverhouse,PC,58-7703341
3,Portugal,"74,532.02",59752.32,4/2/2020,Beauty,Hessel-Stiedemann,Celine Tumasian,Aurelie Wren,PC,14-6700183
4,Spain,"178,763.42",146621.76,12/22/2019,Games,Johns and Sons,Emalia Dinse,Bertha Walbrook,Tablet,15-8765160

## Mising values

In [6]:
df.isna().sum()

country              0
 order_value_EUR     0
 cost                0
date                 0
category             0
customer_name        0
sales_manager        0
sales_rep            0
device_type          0
order_id             0
dtype: int64

In [7]:
df.dtypes

country               object
 order_value_EUR      object
 cost                float64
date                  object
category              object
customer_name         object
sales_manager         object
sales_rep             object
device_type           object
order_id              object
dtype: object

## Revenue analysis

In [8]:
# the total revenue, total cost and total profit for the entire dataset

df.columns = df.columns.str.strip()
df['order_value_EUR'] = pd.to_numeric(df['order_value_EUR'].astype(str).str.replace(',',''), errors='coerce')
df["profit"] = df["order_value_EUR"] - df["cost"]
print(df[['order_value_EUR','cost','profit']].sum().round(2))

order_value_EUR    1.133617e+08
cost               9.436931e+07
profit             1.899243e+07
dtype: float64

In [9]:
# country generates the highest total revenue & the highest average order value

df.groupby('country')['order_value_EUR'].agg(['sum','mean']).sort_values('sum', ascending = False).head(1)

                  sum           mean
country
Portugal  27796361.83  116302.769163

In [10]:
# product category has the highest profit margin on average

df.groupby('category')['profit'].mean().sort_values(ascending = False).head(1)

category
Accessories    22397.038
Name: profit, dtype: float64

In [11]:
# the top 5 sales managers by total revenue and by total profit

df.groupby('sales_manager')[["profit",'order_value_EUR']].sum().sort_values("order_value_EUR",ascending = False).head(5)

                     profit  order_value_EUR
sales_manager
Celine Tumasian  4670107.56      27796361.83
Othello Bowes    4335004.57      25900678.42
Maxie Marrow     3293517.05      19637204.45
Jessamine Apark  2052054.46      12115617.24
Hube Corey        899285.06       5548035.05

In [13]:
# sales rep closes the highest average order value

df.groupby('sales_rep')['order_value_EUR'].agg(['mean','count']).sort_values('mean', ascending=False).head(10)

                              mean  count
sales_rep
Jocelyn Laurentino   132434.109091     22
Corene Shirer        130133.076038     53
Mellicent Mattys     129062.653810     21
Bernadine Fullagar   125546.424667     15
Wat Bowkley          123379.100870     23
Winny Agnolo         123040.468684     38
Tarrah Castelletti   120188.829211     38
Jay Morefield        119478.381154     26
Amelina Piscopiello  118842.145714     56
Hortense Gerring     118465.710962     52

In [ ]:
# Key Findings

1. Portugal Generates the highest revenue.

2. The most protiable item is Accessories

3. Jocelyn Laurentino Closes the highest average deal.